# Generated by Django 5.0.6 on 2026-09-28 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sunflower, Gypsophila Tango', max_length=100)),
                ('variedad', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Sector Norte 1', max_length=100)),
                ('coordenadas_centro', models.CharField(help_text='Lat,Lng para centrar el mapa', max_length=100)),
                ('area_hectareas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo - Operando'), ('RIEGO', 'En Riego'), ('ALERTA', 'Alerta Fitosanitaria'), ('MANTENIMIENTO', 'En Mantenimiento')], default='ACTIVO', max_length=20)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectores', to='core.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Cuadrilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Cuadrilla Cosecha Alfa', max_length=100)),
                ('tipo', models.CharField(choices=[('COSECHA', 'Cosecha'), ('PODADO', 'Podado'), ('RIEGO', 'Riego y Fertirriego'), ('MANTENIMIENTO', 'Mantenimiento')], max_length=20)),
                ('supervisor', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sector_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuadrillas', to='core.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('foto_url', models.URLField(blank=True, help_text='URL del avatar', null=True)),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajadores', to='core.cuadrilla')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudTraslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Motivo operativo de la reasignación')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Firma'), ('ACEPTADO', 'Aceptado por Biometría'), ('RECHAZADO', 'Rechazado por el Trabajador')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('firma_biometrica_hash', models.CharField(blank=True, help_text='Hash criptográfico de WebAuthn', max_length=255, null=True)),
                ('cuadrilla_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_entrantes', to='core.cuadrilla')),
                ('cuadrilla_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_salientes', to='core.cuadrilla')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='core.trabajador')),
            ],
        ),
    ]
