# Generated by Django 5.0.6 on 2026-09-28 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('RIEGO', 'Riego'), ('FERTIRRIEGO', 'Fertirriego'), ('PODA', 'Poda'), ('FUMIGACION', 'Fumigación / Control de Plagas'), ('COSECHA', 'Cosecha')], max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CURSO', 'En Curso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuadrilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades', to='core.cuadrilla')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.sector')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('volumen_cajas', models.IntegerField(help_text='Cantidad de cajas cosechadas')),
                ('calidad', models.CharField(choices=[('A1', 'Exportación (A1)'), ('A2', 'Exportación (A2)'), ('B1', 'Mercado Local (B1)'), ('B2', 'Mercado Local (B2)'), ('RECHAZO', 'Rechazo / Merma')], max_length=20)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosechas', to='core.sector')),
            ],
        ),
    ]
