# Generated by Django 5.0.6 on 2026-10-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='coordenadas_centro',
        ),
        migrations.AddField(
            model_name='sector',
            name='coordenadas_poligono',
            field=models.TextField(blank=True, help_text='JSON array de coordenadas [[lat,lng], [lat,lng]...]', null=True),
        ),
    ]
